### PR TITLE
Fix c docs

### LINKED ISSUE #194: Wasm-ld error in the C/C++ section on creating a component
Following the docs to create a new component from C/C++, the compilation stops with an error from wasm-ld: `undefined symbol: exports_example_add`. I'm using the clang from WASI SDK, and the most recent version of wit-bindgen, 0.37.0 at the time of writing. I can create wasm modules with WASI SDK an they run in wasmtime fine. But I just can't complete the example for C++. 
Am I missing some command? I'm using the command given in the docs: `clang add.c example.c example_component_type.o -o add-core.wasm -mexec-model=reactor`

### PR DESCRIPTION
**Pull request by seanisom**
Fixes #194 

Fixed two problems with the C docs and example host:
1. wit-bindgen has changed the names of exported C functions since the docs were originally written
2. Code written against the P1 adapter in wasmtime now requires the host to explicitly add wasi to the linker, and the P1 adapter must be kept up to date with the wastime version in the `example-host` as wasmtime updates with wasi-0.2.X patch releases. 

Examples tested and working on Win11 and MacOS 14.3

### CODE REVIEW

File: component-model/examples/example-host/src/sync_add.rs [hunk 1]
```diff
@@ -19,8 +20,10 @@ pub fn add(path: PathBuf, x: i32, y: i32) -> wasmtime::Result<i32> {
     let wasi_view = States::new();
     let mut store = Store::new(&engine, wasi_view);
     // Construct linker for linking interfaces.
-    // For this simple adder component, no need to link additional interfaces.
-    let linker = Linker::new(&engine);
+    // For this simple adder component, no need to manually link additional interfaces.
+    let mut linker = Linker::new(&engine);
+    // Add wasi exports to linker to support io interfaces
+    wasmtime_wasi::add_to_linker_sync(&mut linker).expect("Coould not add wasi to linker");
```
Comment (kate-goldenring) [inline component-model/examples/example-host/src/sync_add.rs:26]: Spoooky
```suggestion
    wasmtime_wasi::add_to_linker_sync(&mut linker).expect("Could not add wasi to linker");
```

**Review by kate-goldenring — APPROVED** [review]
Thank you @seanisom!
